<?php

class Di_Blocks_Config {

	/**
	 * Block Attributes
	 *
	 * @var block_attributes
	 */
	public static $block_attributes = null;

	public static function get_block_attributes() {

		if ( null === self::$block_attributes ) {

			self::$block_attributes = array(
				'di-blocks/headline'  => array(
					'slug'        => 'di-blocks/headline',
					'title'       => __( 'Heading', 'di-blocks' ),
					'description' => __( 'Write the heading with advance controls.', 'di-blocks' ),
					'default'     => true,
					'attributes'  => array(
						'LoadGoogleFonts'	=> false,
						'FontFamily'		=> '',
						'FontWeight'		=> '',
						'FontSubset'		=> '',
						'FontSize'			=> '',
						'FontSizeType'		=> 'px',
						'FontSizeTablet'	=> '',
						'FontSizeMobile'	=> '',
						'LineHeight'		=> '',
						'LineHeightType'	=> 'px',
						'LineHeightTablet'	=> '',
						'LineHeightMobile'	=> '',
						'TextTransform'		=> 'none',
						'LetterSpacing'		=> '',
						'HeadColor'			=> '',
						'HeadBgColor'		=> '',
						'HeadLinksColor'	=> '',
						'HeadLinksHvrColor'	=> '',
						'BorderRadius'		=> '',
						'BorderStyle'		=> 'none',
						'BorderWidth'		=> '',
						'BorderColor'		=> '',
						'PaddingTop'		=> '',
						'PaddingRight'		=> '',
						'PaddingBottom'		=> '',
						'PaddingLeft'		=> '',
						'MarginTop'			=> '0',
						'MarginRight'		=> '',
						'MarginBottom'		=> '0',
						'MarginLeft'		=> '',
					),
				),
				'di-blocks/google-map'  => array(
					'slug'        => 'di-blocks/google-map',
					'title'       => __( 'Google Map', 'di-blocks' ),
					'description' => __( 'Display Google map of your location.', 'di-blocks' ),
					'default'     => true,
					'attributes'  => array(
						'PaddingTop'		=> '',
						'PaddingRight'		=> '',
						'PaddingBottom'		=> '',
						'PaddingLeft'		=> '',
						'MarginTop'			=> '',
						'MarginRight'		=> '',
						'MarginBottom'		=> '',
						'MarginLeft'		=> '',
					),
				),
				'di-blocks/icon'  => array(
					'slug'        => 'di-blocks/icon',
					'title'       => __( 'Icon', 'di-blocks' ),
					'description' => __( 'Display icon.', 'di-blocks' ),
					'default'     => true,
					'attributes'  => array(
						'IconSize'			=> '40',
						'IconRotate'		=> '',
						'IconColor'			=> '',
						'IconBgColor'		=> '',
						'BorderRadius'		=> '',
						'BorderStyle'		=> 'none',
						'BorderWidth'		=> '',
						'BorderColor'		=> '',
						'PaddingTop'		=> '',
						'PaddingRight'		=> '',
						'PaddingBottom'		=> '',
						'PaddingLeft'		=> '',
						'MarginTop'			=> '',
						'MarginRight'		=> '',
						'MarginBottom'		=> '',
						'MarginLeft'		=> '',
					),
				),
				'di-blocks/paragraph'  => array(
					'slug'        => 'di-blocks/paragraph',
					'title'       => __( 'Paragraph', 'di-blocks' ),
					'description' => __( 'Write the paragraph with advance controls.', 'di-blocks' ),
					'default'     => true,
					'attributes'  => array(
						'LoadGoogleFonts'	=> false,
						'FontFamily'		=> '',
						'FontWeight'		=> '',
						'FontSubset'		=> '',
						'FontSize'			=> '',
						'FontSizeType'		=> 'px',
						'FontSizeTablet'	=> '',
						'FontSizeMobile'	=> '',
						'LineHeight'		=> '',
						'LineHeightType'	=> 'px',
						'LineHeightTablet'	=> '',
						'LineHeightMobile'	=> '',
						'TextTransform'		=> 'none',
						'LetterSpacing'		=> '',
						'DropCap'			=> false,
						'DropCapSize'		=> '60',
						'DropCapGap'		=> '2',
						'DropCapColor'		=> '',
						'Color'				=> '',
						'BgColor'			=> '',
						'LinksColor'		=> '',
						'LinksHvrColor'		=> '',
						'BorderRadius'		=> '',
						'BorderStyle'		=> 'none',
						'BorderWidth'		=> '',
						'BorderColor'		=> '',
						'PaddingTop'		=> '',
						'PaddingRight'		=> '',
						'PaddingBottom'		=> '',
						'PaddingLeft'		=> '',
						'MarginTop'			=> '',
						'MarginRight'		=> '',
						'MarginBottom'		=> '',
						'MarginLeft'		=> '',
					),
				),
				'di-blocks/divider'  => array(
					'slug'        => 'di-blocks/divider',
					'title'       => __( 'Divider', 'di-blocks' ),
					'description' => __( 'Add a divider between blocks.', 'di-blocks' ),
					'default'     => true,
					'attributes'  => array(
						'Alignment' 		=> 'center',
						'Style'				=> 'solid',
						'Color'				=> '#000000',
						'BorderHeight'		=> '2',
						'BorderWidth'		=> '30',
						'DividerHeight'		=> '5',
						'IconStatus' 		=> 'center',
						'Icon' 				=> 'fas fa-star',
						'IconGap' 			=> '10',
						'IconSize' 			=> '25',
						'IconColor' 		=> '#000000',
						'PaddingTop'		=> '',
						'PaddingRight'		=> '',
						'PaddingBottom'		=> '',
						'PaddingLeft'		=> '',
						'MarginTop'			=> '',
						'MarginRight'		=> '',
						'MarginBottom'		=> '',
						'MarginLeft'		=> '',
					),
				),
				'di-blocks/button'  => array(
					'slug'        => 'di-blocks/button',
					'title'       => __( 'Button', 'di-blocks' ),
					'description' => __( 'Display a button with advance options.', 'di-blocks' ),
					'default'     => true,
					'attributes'  => array(
						'LoadGoogleFonts'	=> false,
						'FontFamily'		=> '',
						'FontWeight'		=> '',
						'FontSubset'		=> '',
						'FontSize'			=> '',
						'FontSizeType'		=> 'px',
						'FontSizeTablet'	=> '',
						'FontSizeMobile'	=> '',
						'LineHeight'		=> '',
						'LineHeightType'	=> 'px',
						'LineHeightTablet'	=> '',
						'LineHeightMobile'	=> '',
						'TextTransform'		=> 'none',
						'LetterSpacing'		=> '',
						'Color'				=> '#000000',
						'BgColor'			=> '#ffffff',
						'HvrColor'			=> '#ffffff',
						'HvrBgColor'		=> '#000000',
						'BorderRadius'		=> '5',
						'BorderStyle'		=> 'solid',
						'BorderWidth'		=> '2',
						'BorderColor'		=> '#000000',
						'PaddingTop'		=> '6',
						'PaddingRight'		=> '15',
						'PaddingBottom'		=> '6',
						'PaddingLeft'		=> '15',
						'MarginTop'			=> '10',
						'MarginRight'		=> '',
						'MarginBottom'		=> '10',
						'MarginLeft'		=> '',
					),
				),
				
			);
		}
		return self::$block_attributes;
	}
	
}
